parallelized lipidblast and reads more info
rformassspectrometry/CompoundDb pull request #117
Opened 2024-07-18 15:17 UTC by pratarora

I changed compound_tbl_lipidblast and dependent function to allow it to read more information from the json files,and parallelized it to allow faster reading.

I have tested it on old and new lipidblast as described in https://github.com/rformassspectrometry/CompoundDb/issues/114
Best regards
Prateek

2024-07-23 11:00 UTC, jorainer requested changes
Thanks for the contribution @pratarora ! Code looks great, I will then fix the unit tests after merging. 

Can you however please add yourself as a contributor (`role = c("ctb")`) to the DESCRIPTION file and to the `@author tag of the `compound_tbl_lipidblast()` function?

2024-07-25 09:12 UTC, pratarora commented on R/createCompDbPackage.R
> +#' - `spectrum`: the spectrum data.
Thanks @jorainer ! done with the changes.

2024-07-29 09:21 UTC, jorainer approved these changes
Thanks @pratarora ! Will merge and then push to Bioconductor

2024-07-29 09:24 UTC, merged

2024-07-31 11:23 UTC, jorainer commented
@pratarora , hope it's OK, but I added you also as a contributor to the [RforMassSpectrometry page](https://www.rformassspectrometry.org/contributions/)

2024-07-31 11:32 UTC, pratarora commented
Thanks a lot, @jorainer !